name: deeplab
model: deeplab
dataset: cityscapes
model_clip: False

batch_size: 8

checkpointdir: /path/to/folder/
ckpt: baseline.ckpt

goldpath: null
generate: True
iterations: 1e12
testsamples: 100

disableconsolelog: False

### Ignore
mode: test
data_dir: /path/to/data/
size: 769
num_gpus: 1
activation: max
pretrained: True
nan: True
loss: ce
grad_clip: null
epochs: 100
lr: 0.01
wd: 1e-4
scheduler: poly
optimizer: sgd
error_model: block
inject_p: 0.0
inject_epoch: 0
seed: 0
comment: test
