name: c100_res44_test_02_gelu6_nans
mode: validate
ckpt: c100_res44_hard_gelu6_nans-epoch=99-val_acc=0.70.ckpt
dataset: cifar100
num_gpus: 1
model: hard_resnet44
loss: bce
clip: !!float 0.05
order: relu-bn
activation: gelu6
affine: true
epochs: 200
batch_size: 128
lr: !!float 1e-3
wd: !!float 1e-3
optimizer: adamw
seed: 0
error_model: square
inject_p: !!float 0.75
inject_epoch: 0
comment: Gelu6 and nan filter
nan: true