name: deeplabv3_clip_train_aware
model: deeplab
dataset: cityscapes
model_clip: True
batch_size: 8
ckpt: clip_train_aware.ckpt
mode: test
size: 769
num_gpus: 1
activation: max
pretrained: True
nan: True
loss: ce
grad_clip: null
epochs: 100
lr: 0.01
wd: 1e-4
scheduler: poly
optimizer: sgd
error_model: block
inject_p: 0.0
inject_epoch: 0
seed: 0
comment: test
freeze: false


#goldpath: null
#generate: True
#iterations: 1e12
#testsamples: 100

#disableconsolelog: False
#checkpointdir: /path/to/folder/
#data_dir: /path/to/data/

### Ignore